server_name: s4
chat_server:
  host: localhost
  port: 12345
exchange_server:
  host: localhost
  port: 5555
remote_servers:
  - name: s2
    host: 127.0.0.1
    port: 5552
  

# server_name: s2
# chat_server:
#   host: localhost
#   port: 12342
# exchange_server:
#   host: localhost
#   port: 5552
# remote_servers:
#   - name: s4
#     host: 127.0.0.1
#     port: 5555
