server_name: s4
chat_server:
  host: localhost
  port: 12345
exchange_server:
  host: localhost
  port: 5555
remote_servers:
  - name: s1
    host: 127.0.0.1
    port: 5555
  - name: s2
    host: localhost
    port: 5555
  - name: s3
    host: localhost
    port: 5555
  - name: s5
    host: localhost
    port: 5555
  

